logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.coyote.http11: debug

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

oauth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: http://localhost:3000/oauth/redirected/kakao
    client_secret: ${KAKAO_CLIENT_SECRET}
    scope: profile_nickname, profile_image