# Generated by Django 3.2.23 on 2023-12-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultfeedback',
            name='rec_pd',
            field=models.TextField(blank=True),
        ),
    ]
