# Generated by Django 3.2.23 on 2023-12-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_resultfeedback_rec_pd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultfeedback',
            old_name='rec_pd',
            new_name='rec_pd1',
        ),
    ]
